import { DanielData, MaishaData } from "./interfaces";

export const danielData: DanielData = {
  classificationReport: {
    metrics: [
      {
        label: "Amusement",
        precision: 0.79,
        recall: 0.89,
        f1Score: 0.84,
        support: 61,
      },
      {
        label: "Anger",
        precision: 0.87,
        recall: 0.83,
        f1Score: 0.85,
        support: 65,
      },
      {
        label: "Disgust",
        precision: 0.68,
        recall: 0.75,
        f1Score: 0.71,
        support: 63,
      },
      {
        label: "Fear",
        precision: 0.77,
        recall: 0.74,
        f1Score: 0.76,
        support: 69,
      },
      {
        label: "Inspiration",
        precision: 0.77,
        recall: 0.83,
        f1Score: 0.8,
        support: 58,
      },
      {
        label: "Joy",
        precision: 0.85,
        recall: 0.83,
        f1Score: 0.84,
        support: 64,
      },
      {
        label: "Neutral",
        precision: 0.72,
        recall: 0.71,
        f1Score: 0.71,
        support: 72,
      },
      {
        label: "Sadness",
        precision: 0.79,
        recall: 0.69,
        f1Score: 0.74,
        support: 59,
      },
      {
        label: "Tenderness",
        precision: 0.81,
        recall: 0.8,
        f1Score: 0.8,
        support: 49,
      },
      // Gap row for better spacing
      {
        label: "",
        precision: null,
        recall: null,
        f1Score: null,
        support: null,
      },
      {
        label: "Accuracy",
        precision: null,
        recall: null,
        f1Score: 0.78,
        support: 560,
      },
      {
        label: "Macro Average",
        precision: 0.79,
        recall: 0.78,
        f1Score: 0.78,
        support: 560,
      },
      {
        label: "Weighted Average",
        precision: 0.78,
        recall: 0.78,
        f1Score: 0.78,
        support: 560,
      },
    ],
    accuracy: 78.21,
    loss: undefined,
  },
  confusionMatrixImage: "/daniel-confusion-matrix.png",
};

export const maishaData: MaishaData = {
  classificationReport: {
    metrics: [
      {
        label: "Amusement",
        precision: 0.81,
        recall: 0.91,
        f1Score: 0.85,
        support: 55,
      },
      {
        label: "Anger",
        precision: 0.62,
        recall: 0.76,
        f1Score: 0.68,
        support: 54,
      },
      {
        label: "Disgust",
        precision: 0.69,
        recall: 0.76,
        f1Score: 0.72,
        support: 50,
      },
      {
        label: "Fear",
        precision: 0.74,
        recall: 0.72,
        f1Score: 0.73,
        support: 71,
      },
      {
        label: "Inspiration",
        precision: 0.79,
        recall: 0.68,
        f1Score: 0.73,
        support: 72,
      },
      {
        label: "Joy",
        precision: 0.82,
        recall: 0.76,
        f1Score: 0.79,
        support: 54,
      },
      {
        label: "Neutral",
        precision: 0.82,
        recall: 0.69,
        f1Score: 0.75,
        support: 89,
      },
      {
        label: "Sadness",
        precision: 0.70,
        recall: 0.83,
        f1Score: 0.76,
        support: 60,
      },
      {
        label: "Tenderness",
        precision: 0.78,
        recall: 0.73,
        f1Score: 0.75,
        support: 55,
      },
      // Gap row for better spacing
      {
        label: "",
        precision: null,
        recall: null,
        f1Score: null,
        support: null,
      },
      {
        label: "Accuracy",
        precision: null,
        recall: null,
        f1Score: 0.75,
        support: 560,
      },
      {
        label: "Macro Average",
        precision: 0.75,
        recall: 0.76,
        f1Score: 0.75,
        support: 560,
      },
      {
        label: "Weighted Average",
        precision: 0.76,
        recall: 0.75,
        f1Score: 0.75,
        support: 560,
      },
    ],
    accuracy: 75.179,
    loss: 3.29692,
  },
  confusionMatrixImage: "/maisha-confusion-matrix.png",
};
